AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Simple state machine with ECS task'

Parameters:
  Cluster:
    Type: String
    Description: cluster arn
    Default: arn:aws:ecs:us-east-1:xxx:cluster/far-step-Fargate-1UFKEO406KYW6-FGCluster-1JRWDCKEPZA1L
  Task:
    Type: String
    Description: task arn
    Default: arn:aws:ecs:us-east-1:xxx:task-definition/step-fn-tasks

Resources:

# Note: in parameters the network config is needed for fargate
# TODO: import vals

  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionString: !Sub |
        {
          "StartAt": "Run an ECS Task and wait for it to complete",
          "States": {
            "Run an ECS Task and wait for it to complete": {
              "Type": "Task",
              "Resource": "arn:aws:states:::ecs:runTask.sync",
              
              
              "Parameters": {
                          "Cluster": "${Cluster}",
                          "TaskDefinition": "${Task}",
                          "LaunchType": "FARGATE",
                          "NetworkConfiguration": {
                            "AwsvpcConfiguration": {
                              "SecurityGroups": ["sg-0c6ffdc6652caf6ab"],
                              "Subnets":["subnet-08405970c9799b2b8","subnet-09d36ecc61d529931"]
                            }
                          }

                      },
              "End": true
              }
            }
          }
      RoleArn: !GetAtt StateMachineRole.Arn

  StateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                  - "ecs:RunTask"
                  - "ecs:StopTask"
                  - "ecs:DescribeTasks"
                  - "events:PutTargets"
                  - "events:PutRule"
                  - "events:DescribeRule"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "logs:CreateLogGroup"
                  - "iam:PassRole"
                Resource: '*'
                  
